name: CI

on:
  pull_request:
    types: [opened,reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke CircleCI PR Workflow
      env:
        CIRCLE_TOKEN: "a7ba232028b86cff5396141a7dfa7f25bf451eba"
        PROJECT_SLUG: gh/EngineersBox/terraform-provider-instaclustr
      run: |
        curl -X POST \
        -H 'Circle-Token: ${CIRCLE_TOKEN}' \
        -d '{"branch":"${GITHUB_REF##*/}", "parameters":{"is-pr":true}}' \
        https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline
