name: CI

on:
  pull_request:
    types: [opened,reopened]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Invoke CircleCI PR Workflow
      env:
        CIRCLE_TOKEN: ${{ secrets.CIRCLE_TOKEN }}
        CIRCLE_BRANCH: ${{ github.head_ref }}
        PROJECT_SLUG: gh/EngineersBox/terraform-provider-instaclustr
      run: |
        curl -X POST \
        -H 'Circle-Token: ${CIRCLE_TOKEN}' \
        -H 'Content-Type: application/json' \
        -H 'Accept: application/json' \
        -d "{\"branch\":\"${CIRCLE_BRANCH}\", \"parameters\":{\"is-pr\":true}}" \
        https://circleci.com/api/v2/project/${PROJECT_SLUG}/pipeline
